### ISSUE TITLE
Loving the idea of larger ladders!

### ISSUE THREAD

**Issue by Slendykins** [Inoyuuuuu/lcMod_GiantExtensionLadders#1]
Hey just wanted to say that I love this mod,

I can finally snipe my teammates from across even _larger gaps_ now!

I was wondering if there could be a config option to disable the retraction? We like to play with the Permanent_Ladder mod and already make pathways of sorts to work around some moons that are flooded or if they are eclipsed, and these new ones open up much more possibility for new paths!

**Comment by Inoyuuuuu** [comment]
Sounds good, will look into this. What I can do now is add adjustable ladder retraction timer to the config (that's not exactly what you asked for, but you could make them last very long). :)

**Comment by Slendykins** [comment]
Brilliant thank you very much! :D We were brainstorming today as we can get quicker paths to the ship using these on moons like Kast! I'll let you know if I run into any problems!!
